remote_theme: pages-themes/cayman@v0.2.0
title: Docker Pull Auto - Automatically pull docker images when push
description: Idea of this project is to pull docker images automatically on server whenever there is push. Also deletes old image if exist
google_analytics: G-JEDLKV3VKC
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
links:
  # - text: Getting Started
  #   link: /getting-started.html
  - text: How to add docker container app for auto pull in config json
    link: /how-to-add-docker-container-app.html
  - text: What is HOOK_SECRET and How to create HOOK_SECRET
    link: /how-to-create-hook-secret.html
  - text: How to create multiple config based on environment
    link: /how-to-create-multiple-config-based-on-env.html
  - text: How to encrypt config.json
    link: /how-to-encrypt-config-json.html
  - text: How to add environment file for Docker App/ Config App
    link: /how-to-add-environment-file-for-config-app.html
